[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/boot/linker.ld", "-Cforce-frame-pointers=yes"
]

[target.'cfg(target_os = "none")']
runner = "make run"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
